version: "3"

services:
    server:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
          - "8080:80"
          - "443:443"
        volumes:
          - ./projects:/var/www/
          - ./nginx/conf.d/app.conf/:/etc/nginx/conf.d/default.conf/
        networks:
          - internal
    php:
        build:
          context: ./php
          dockerfile: Dockerfile
        container_name: php
        networks:
          - internal
        volumes:
          - ./projects/:/var/www/
    db:
      image: mysql:5.7
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: mypassword
        MYSQL_ROOT_PASSWORD: mypassword
        MYSQL_DATABASE: testdb
      volumes:
        - dbdata:/var/lib/mysql/
      networks:
        - internal
networks:
  internal:
    driver: bridge
volumes:
  dbdata:
    driver: local